# Site settings
title: Calvary Baptist Church
header-img: img/home-bg.png
post-header-img: img/class-bg.png
logo-img: img/3crosslogo.png
email: saintpetercalvarybaptistchurch@gmail.com
description: "Calvary Baptist Church in St. Peter, Minnesota"
baseurl: ""
url: "http://saintpetercalvarybaptistchurch.com"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate]
