---
layout: post
title: The Goodness of God
date: 2021-03-06 00:30:00
author: "Pastor Dave Johnson"
---

If there is a subject worth a solid pulpit proclamation, together with man giving a worthwhile attentive ear, it is the subject regarding the goodness of God.   True, we all have listened to the complaint of the natural man concerning those adverse circumstances in "his" world, and it is generally a self-driven sentiment against the Lord.  We live in a society that is not only anti-God, but it also holds to the ungodly practice of blame shifting.  Here's the truth concerning that matter; God is not the reason for the world's problems, but man is because of his sinful, fallen condition.  The Bible has the answer regarding the good and evil question so prominent in the world, and the godly Christian recognizes that everything that God created was GOOD (Genesis 1:31),  It is the misconstrued, sinful heart of man that needs to come to a repentant awareness of the truth of God's goodness.  In the context of fallen man's wrong-filled judgment, the Apostle Paul addresses that dilemma: "Despisest thou the riches of his goodness and forbearance and longsuffering; not knowing that the goodness of God leadeth thee to repentance" (Romans 2:4).  So, let's get back to the Bible to see anew the goodness of God, recognizing that GOOD TRUTH which will change the spiritual direction of lives, yours included.

The goodness of God is found in the very nature of God; that's who he is. and "good is of God" (3 John 11).  We need to "Behold therefore the goodness of God" (Romans 11:22).  It was Jesus himself who told Philip, "He that hath seen me hath seen the Father" (John 14:9).  The Lord Jesus revealed the very nature of God as he "went about doing good" (Acts 10:38).  He is still active in doing good, most recognized by those who know the God of the Bible.  You see, goodness is one of the Lord's attributes; God by nature is without any dispute: GOOD.  The Word of God is clear concerning that truth:  "The Lord is good to all and his tender mercies are over all his works" (Psalm 145:9).  The reason WHY is found in the Who, and WHAT he does: "Thou art good, and doest good" (Psalm 119:68).  The Psalmist doesn't end that verse there; as he proclaims God's goodness, he then asks the Lord to "teach me thy statutes" (v. 68).   So, may we all be taught the statutes of God, including his goodness and in so learning of his goodness, may we refrain from the world's mindset of defaming the goodness of God.   Let us remember that "the goodness of God endureth continually" (Psalm 52:1).  He hasn't changed in who he is, and that enduring good is plentiful: "no good thing will he withhold from those who walk uprightly" (Psalm 84:11).   May it have an abiding effect in your life; if you are born of his Spirit, remember, you are the handiwork of God, his creation, and most importantly, his new creation (2 Corinthians 5:17)..   "Being confident of this very thing, that he which hath begun a good work in you will perform it until the day of Jesus Christ" (Philippians 1:6).  That good work is NOW being performed in the believer's life, accomplished by God in his goodness, because "Thou art good, and doest good." 